### PR TITLE
Maintenance, including base image update to 22.04

### PR DESCRIPTION
**Pull request by mhasself**
Also:
- rename test_image.py to test_and_push_image.py
- Remove PYTHON_EXECUTABLE from cmake line
- include libbz2-dev

### CODE REVIEW

**Comment by mhasself** [comment]
Not super urgent, but I want to start linking against newer spt3g in so3g, and this is a stepping stone.

**Review by BrianJKoopman — APPROVED** [review]
Looks good to me, thanks for the updates! I'll get these changes deployed today. Should I push up a new build for the latest `spt3g_software` version?

**Comment by mhasself** [comment]
> Looks good to me, thanks for the updates! I'll get these changes deployed today. Should I push up a new build for the latest `spt3g_software` version?

That would be great, if it doesn't violate docker tag integrity in some way.

**Comment by BrianJKoopman** [comment]
The image [0.3-276-gbe879ce](https://hub.docker.com/layers/simonsobs/spt3g/0.3-276-gbe879ce/images/sha256-b0ffb5f27870e27ba8827002d6adf1068a3792e71ee8a58e39720061aa2ba29b?context=explore) has these changes in it.

**Pull request merged**
